#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, use it as
#       the shell for the next line:
#
#           SHELL=/bin/bash ./gradlew
#
#   (2) The Java home directory needs to be set to point to the location of
#       your Java installation.
#
##############################################################################

set -e

DIRNAME="$(cd "$(dirname "$0")" && pwd)"
cd "$DIRNAME" || exit 1

if [ -z "$JAVA_HOME" ] ; then
    JAVA_HOME="$(java -XshowSettings:properties -version 2>&1 | grep 'java.home' | awk '{print $NF}')"
fi

if [ ! -e "$DIRNAME/gradle/wrapper/gradle-wrapper.jar" ] ; then
    echo "Error: gradle-wrapper.jar not found in gradle/wrapper directory." >&2
    exit 1
fi

exec "$JAVA_HOME/bin/java" \
    -Dorg.gradle.appname="$APP_BASE_NAME" \
    -classpath "$DIRNAME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain "$@"
